development:
  adapter: sqlite3 
  database: db/bomb_development.sqlite3
  pool: 32
  timeout: 5000

test:
  adapter: sqlite3 
  database: db/bomb_test.sqlite3
  pool: 32
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 32
  timeout: 5000
