development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: bomb_development
  pool: 5
  username: root
  password: 'password'
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: bomb_test
  pool: 5
  username: root
  password: 'password'
  socket: /tmp/mysql.sock
